sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: nhdQ+FOO2j9u15nhWL/ONmh/TAR9Lz6IS44Ra2cGliSxlRiRoG6f3qZMYqMUBa3WVzMLJQY5bC/glJL06oDxQST++BOYOPT5xCYWgeniTdyQowINpkICbri0vbR7KZ6g5Bx2qCPD5CCrutrC2o0aLmBQe5kZTXGc7krBd4o9C8NCS2dcHbUoRJVAoT2j9ZnTLGBeu6/6S8de4eEJ0nvD497XIuS/hkGo5jM8/1du6g3mMIje4UK9srv/sAUQN3tSkpGiEV2sv2NQ8VS+LQ4kZzqD5JULC0C3zr7uGhvUjbqqb6JVRo3lm0HdPKs2LzIlBCMJVn4y8kC8swJNV9q6gyPQOAUwngE99wrJeezJBZmmT/ati0OFBGswz5wprTOlW9pIPlYuz6bDsN6YuoVqmwbd2e5KtEqKPUTjNAHwQKw20Q5Ko0mLX3mHjxugDieCDFtjCO4Esuxz4+gUElXvYJEIa0pFvAi8ZcO+vhpJdtipIMnMpDuhn1fPuKWL/H04w9etzEw91wkyUn3/SV9WypcqCB4Q4HpOvrl7ZGEp+4ZhsaToPduo+U9aBti1I9/BjFofj0XQm2nNdazYwg7qDIhkZ5UxcH0RqDHQXX6+xry9ToWgICLDeBvV3ZTQwmrPTLQb8oyh1K00EROB/8wv/Mdr1xsKl5GgicVV38XI/X0=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Mr.-Honey-s-Correspondence-Dictionary--English-German-_3223
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy